language: ruby
rvm:
  - 1.8.7
  - 1.9.3
gemfile: src/Gemfile
env: 
  - SUITE=cucumber
  - SUITE=spec
before_install:
  - sed -i s/'pg'/'sqlite3'/ src/Gemfile
install:
  - cd src 
  - bundle install --path bundle
before_script:
  - cp config/database.sqlite config/database.yml
  - bundle exec rake dc:oauth_keys
  - bundle exec rake db:drop
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rake db:seed
  - bundle exec rake db:test:prepare
script:
  - bundle exec rake $SUITE
notifications:
  irc:
    channels:
      - "irc.freenode.org#aeolus"
    use_notice: true
    skip_join: false
    on_success: change
    on_failure: change
