:default_deltacloud_url: http://localhost:3002/api

:auth:
  # supported strategies: database, ldap
  :strategy: database
:groups:
  # allows locally-managed groups
  :enable_local: true
  # allows ldap-managed groups
  :enable_ldap: true
:iwhd:
  :url: http://localhost:9090
  # :oauth:
  #   :consumer_key: consumer_key_here
  #   :consumer_secret: consumer_secret_here

:imagefactory:
  :url: https://localhost:8075/imagefactory
  # :oauth:
  #   :consumer_key: consumer_key_here
  #   :consumer_secret: consumer_secret_here

:session:
  :timeout: 150 # minutes
#  :timeout: 150000000000 # minutes

:action_mailer:
  :delivery_method: sendmail # or smtp
  # use this configuration if you use smtp as delivery_method
  # :smtp_settings:
  #   :address: smtp.gmail.com
  #   :port: 587
  #   :domain: example.aeolusproject.org
  #   :user_name: <username>,
  #   :password: <password>
  #   :authentication: plain
  #   :enable_starttls_auto: true
  :default_url_options:
    :host: localhost/conductor
    :protocol: https
  :default_from: admin@aeolusproject.org
  :password_reset_token_timeout: 120 #minutes
