:default_deltacloud_url: http://localhost:3002/api

:auth:
  # supported strategies: database, ldap
  :strategy: database
:groups:
  # allows locally-managed groups
  :enable_local: true
  # allows ldap-managed groups
  :enable_ldap: true
:iwhd:
  :url: http://localhost:9090
  # :oauth:
  #   :consumer_key: consumer_key_here
  #   :consumer_secret: consumer_secret_here

:imagefactory:
  :url: https://localhost:8075/imagefactory
  # :oauth:
  #   :consumer_key: consumer_key_here
  #   :consumer_secret: consumer_secret_here
